# Minimal rsyslog config for Docker
module(load="imuxsock")
module(load="builtin:omfile" Template="RSYSLOG_TraditionalFileFormat")

# Log mail messages
mail.* /var/log/maillog

# Stop processing after writing to maillog
& stop
